#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 21 11:20:29 2020

@author: davsan06
"""

from astropy.io import fits
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

redmagic_path = '/scratch/davsan06/REDMAGIC_CATALOGUE/'

# Reading catalogue
cat_spec = fits.open(os.path.join(redmagic_path, 'redmagic_dr8_public_v6.3_spectroscopic.fits'))[1].data
cat_spec = pd.DataFrame(np.array(cat_spec).byteswap().newbyteorder())

# Looking for bad flags in error magnitude
cat['MODEL_MAGERR_Z'].min()
cat['MODEL_MAGERR_Z'].max()

# Shuffling observations and taking 5.000 for TRAINING
cat['RA']
cat.info()

cat = cat.sample(frac=1)

cat['RA']
cat.info()

# TRAIN/VALIDATION split
cat_train = cat[:5000]


# Analysing representativeness
plt.hist(cat_train['Z_SPEC'], bins = 40, histtype = 'step', label = 'Spectros')
plt.hist(cat_train['ZREDMAGIC'], bins = 40, histtype = 'step', label = 'Photo')
plt.xlabel('z')
plt.ylabel('$N_{gal}$')
plt.legend()
plt.show()
















